Models/ErrorViewModel.cs
namespace tl2_tp10_2023_SantiagoECastillo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Tablero.cs
namespace tl2_tp10_2023_SantiagoECastillo.Models{
    public class Tablero{
        private int idTablero;
        private int idUsuarioPropietario;
        private string? nombre;
        private string? descripcion;

        public int IdTablero { get => idTablero; set => idTablero = value; }
        public int IdUsuarioPropietario { get => idUsuarioPropietario; set => idUsuarioPropietario = value; }
        public string? Nombre { get => nombre; set => nombre = value; }
        public string? Descripcion { get => descripcion; set => descripcion = value; }
    }
}

Models/Tareas.cs
namespace tl2_tp10_2023_SantiagoECastillo.Models{
    public class Tarea{
        private int idTarea;
        private int idTablero;
        private string? nombreTarea;
        private string? descripcionTarea;
        private string? color;
        private EstadoTarea Estado;
        private int? IdUsuarioAsignado;

        public int IdTarea { get => idTarea; set => idTarea = value; }
        public string? NombreTarea { get => nombreTarea; set => nombreTarea = value; }
        public string? DescripcionTarea { get => descripcionTarea; set => descripcionTarea = value; }
        public string? Color { get => color; set => color = value; }
        public EstadoTarea Estado1 { get => Estado; set => Estado = value; }
        public int? IdUsuarioAsignado1 { get => IdUsuarioAsignado; set => IdUsuarioAsignado = value; }
        public int IdTablero { get => idTablero; set => idTablero = value; }
    }

    public enum EstadoTarea{
        Ideas,
        ToDo, 
        Doing, 
        Review, 
        Done

    }
}

Models/Usuario.cs
namespace tl2_tp10_2023_SantiagoECastillo.Models{
    public class Usuario {
        private int idUsuario;
        private string? nombreUsuario;

        public int IdUsuario { get => idUsuario; set => idUsuario = value; }
        public string? NombreUsuario { get => nombreUsuario; set => nombreUsuario = value; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_SantiagoECastillo.Models;

namespace tl2_tp10_2023_SantiagoECastillo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LoginController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_SantiagoECastillo.Models;
using tl2_tp10_2023_SantiagoECastillo.Repositorio;


namespace tl2_tp10_2023_SantiagoECastillo.Controllers;

public class LoginController : Controller{

    private IUsuarioRepositorio usuarioRepositorio;

    private readonly ILogger<HomeController> _logger;

    public LoginController(ILogger<HomeController> logger){
        _logger = logger;
        usuarioRepositorio = new UsuarioRepositorio();
    }

/*
    public IActionResult Index(){
        return View(new)
    }
    */
}

Controllers/TableroController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_SantiagoECastillo.Models;
using tl2_tp10_2023_SantiagoECastillo.Repositorio;


namespace tl2_tp10_2023_SantiagoECastillo.Controllers;

public class TableroController : Controller{

    private ITableroRepositorio tableroRepositorio;

    private readonly ILogger<HomeController> _logger;

    public TableroController(ILogger<HomeController> logger){
        _logger = logger;
        tableroRepositorio = new TableroRepositorio();
    }


    [HttpGet]
    public IActionResult ObtenerTableros(){
        var tableros = tableroRepositorio.ListarTableros();
        return View(tableros);
    }

    [HttpGet]
    public IActionResult CrearTablero(){
        return View(new Tablero());
    }

    [HttpPost]
    public IActionResult CrearTablero(Tablero tablero){
        tableroRepositorio.CrearTablero(tablero);
        return RedirectToAction("ObtenerTableros");
    }

    [HttpGet]
    public IActionResult EditarTablero(int idTablero){
        var tableroAEditar = tableroRepositorio.ObtenerTablero(idTablero);
        return View(tableroAEditar);
    }

    [HttpPost]
    public IActionResult EditarTablero(Tablero tablero){
        var tableroEditado = tableroRepositorio.ObtenerTablero(tablero.IdTablero);
        tableroEditado.Nombre = tablero.Nombre;
        tableroEditado.Descripcion = tablero.Descripcion;
        tableroEditado.IdUsuarioPropietario = tablero.IdUsuarioPropietario;
        tableroRepositorio.ModificarTablero(tablero.IdTablero, tableroEditado);
        return RedirectToAction("ObtenerTableros");
    }

    //[HttpDelete]
    public IActionResult EliminarTablero(int idTablero){
        tableroRepositorio.EliminarTablero(idTablero);
        return RedirectToAction("ObtenerTableros");
    }
   
}

Controllers/UsuarioController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_SantiagoECastillo.Models;
using tl2_tp10_2023_SantiagoECastillo.Repositorio;


namespace tl2_tp10_2023_SantiagoECastillo.Controllers;

public class UsuarioController : Controller {

    private IUsuarioRepositorio usuarioRepositorio;

    private readonly ILogger<HomeController> _logger;

    public UsuarioController(ILogger<HomeController> logger){
        _logger = logger;
        usuarioRepositorio = new UsuarioRepositorio();
    }


    [HttpGet]
    public IActionResult GetUsuarios(){
        var usuarios = usuarioRepositorio.ObtenerTodosUsuarios();
        return View(usuarios);
    }

    [HttpGet]
    public IActionResult CrearUsuario(){
        return View(new Usuario());
    }

    [HttpPost]
    public IActionResult CrearUsuario(Usuario usuario){
        usuarioRepositorio.CrearUsuario(usuario);
        return RedirectToAction("GetUsuarios");
    }

    [HttpGet]
    public IActionResult EditarUsuario(int idUsuario){
        var usuarioBuscado = usuarioRepositorio.ObtenerUsuarioPorId(idUsuario);
        return View(usuarioBuscado);
    }

    [HttpPost]
    public IActionResult EditarUsuario(Usuario usuario){
        var usuarioBuscado = usuarioRepositorio.ObtenerUsuarioPorId(usuario.IdUsuario);
        usuarioBuscado.NombreUsuario = usuario.NombreUsuario;
        usuarioRepositorio.ModificarUsuario(usuarioBuscado);
        return RedirectToAction("GetUsuarios");
    }

    //[HttpDelete]
    public IActionResult EliminarUsuario(int idUsuario){
        usuarioRepositorio.EliminarUsuarios(idUsuario);
        return RedirectToAction("GetUsuarios");
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tl2_tp10_2023_SantiagoECastillo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tl2_tp10_2023_SantiagoECastillo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tl2_tp10_2023_SantiagoECastillo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="GetUsuarios">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CrearUsuario">Crear</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tablero" asp-action="ObtenerTableros">Tableros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - tl2_tp10_2023_SantiagoECastillo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tablero/CrearTablero.cshtml
@model Tablero

<form asp-controller="Tablero" asp-action="CrearTablero">
    
    <div class="form-group">
        <label asp-for="@Model.Nombre"></label>
        <input asp-for="@Model.Nombre" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="@Model.Descripcion"></label>
        <input asp-for="@Model.Descripcion" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

Views/Tablero/EditarTablero.cshtml
@model Tablero

<form asp-controller="Tablero" asp-action="EditarTablero">
    <input hidden asp-for="@Model.IdTablero">
    <div class="form-group">
        <label asp-for="@Model.Nombre"></label>
        <input asp-for="@Model.Nombre" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="@Model.Descripcion"></label>
        <input asp-for="@Model.Descripcion" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

Views/Tablero/ObtenerTableros.cshtml
@model List<Tablero>

<h2>Usuarios</h2>

<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Id dueño</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var tablero in Model){
            <tr>
                <td>@tablero.Nombre</td>
                <td>@tablero.Descripcion</td>
                <td>@tablero.IdUsuarioPropietario</td>

                <td>
                    <button type="button" class="btn btn-secondary">
                        <a asp-controller="Tablero" asp-action="EditarTablero" asp-route-idTablero="@tablero.IdTablero">Editar</a>
                    </button>

                    <button type="button" class="btn btn-danger">
                        <a asp-controller="Tablero" asp-action="EliminarTablero" asp-route-idTablero="@tablero.IdTablero" onclick="return confirm('Estas seguro que quieres eliminar el tablero @tablero.Nombre ?')">Eliminar</a>
                    </button>
                </td> 
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Tablero" asp-action="CrearTablero">Crear Tablero</a>

Views/Usuario/CrearUsuario.cshtml
@model Usuario

<form asp-controller="Usuario" asp-action="CrearUsuario">
    
    <div class="form-group">
        <label asp-for="@Model.NombreUsuario"></label>
        <input asp-for="@Model.NombreUsuario" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

Views/Usuario/EditarUsuario.cshtml
@model Usuario

<form asp-controller="Usuario" asp-action="EditarUsuario">
    <input hidden asp-for="@Model.IdUsuario">
    <div class="form-group">
        <label asp-for="@Model.NombreUsuario"></label>
        <input asp-for="@Model.NombreUsuario" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

Views/Usuario/GetUsuarios.cshtml
@model List<Usuario>

<h2>Usuarios</h2>

<table>
    <thead>
        <tr>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var usuario in Model){
            <tr>
                <td>@usuario.NombreUsuario</td>
                <td>
                    <button type="button" class="btn btn-secondary">
                        <a asp-controller="Usuario" asp-action="EditarUsuario" asp-route-idUsuario="@usuario.IdUsuario">Editar</a>
                    </button>

                    <button type="button" class="btn btn-danger">
                        <a asp-controller="Usuario" asp-action="EliminarUsuario" asp-route-idUsuario="@usuario.IdUsuario" onclick="return confirm('Estas seguro que quieres eliminar al usuario @usuario.NombreUsuario ?')">Eliminar</a>
                    </button>
                </td> 
            </tr>
        }
    </tbody>
</table>